name: generate animation

on:
  schedule:
    # Runs at 00:00AM UTC
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
    - master

jobs:
  generate:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      # Step 1: Checkout the repository so that you can work with the files in the repo
      - name: Checkout repository
        uses: actions/checkout@v3
      
      # Step 2: Generate the snake SVG
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            assets/github-contribution-grid-snake.svg
            assets/github-contribution-grid-snake-dark.svg?palette=github-dark
          
      # Step 3: Push the SVG to the XXX folder on the main branch
      - name: Push github-contribution-grid-snake.svg to the main branch
        run: |
          git config user.name "DracoYan-111"
          git config user.email "yanlong2944@gmail.com"
          
          git add assets/github-contribution-grid-snake.svg
          git commit -m "Add generated snake SVG to assets folder"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.DRACO_GITHUB_TOKEN }}
